version: '3.8'
name: domina_dev
services:
  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: developer
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
